# Generated by Django 5.0.3 on 2024-03-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_by',
            field=models.CharField(default='superuser', max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
